CREATE TABLE Usuario (
	idUsuario INT IDENTITY,
	nome VARCHAR(45) NOT NULL,
	email VARCHAR(40) NOT NULL,
	senha VARCHAR(20) NOT NULL,
	imgPerfil IMAGE
)

CREATE TABLE Administrador (
	idAdm INT IDENTITY,
	nome VARCHAR(45) NOT NULL,
	email VARCHAR(40) NOT NULL,
	senha VARCHAR(20) NOT NULL,
	imgPerfil IMAGE,
	CPF VARCHAR(13) NOT NULL
)


